---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: arial
    colorlinks: true
    fontsize: '12'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---

<!-- TITLE -->

```{=tex}
\begin{huge}\begin{center}{\bf Tuan Le Khac}\end{center}\end{huge}
\begin{center}{\bf Senior Data Analyst}\end{center}
```
<!-- CONTACT INFO -->

```{=tex}
\begin{center}m: \href{tuanlekhac0905@gmail.com}{tuanlekhac0905@gmail.com} ∙ p: (+84) 328 918 634 ∙ w: \href{https://lktuan.github.io/}{lktuan.github.io} ∙ in: \href{https://www.linkedin.com/in/tuanlekhac/}{tuanlekhac}
\end{center}
\vspace{15pt}
```

<!-- Summary: -->

```{=tex}
\begin{large}
  {\bf Summary}
  \vspace{3pt}
  \hrule
\end{large}
```
- A dynamic and dedicated person, experienced in external audit & corporate finance, and currently working in the risk management field;
- Long-term goal is to continuously accumulate knowledge of the market, operation, risk & strategy in banking & finance, strengthen data analytic skills to provide data-driven business solutions, and contribute to the organization.
\vspace{0.05cm}


<!-- Education: -->

```{=tex}
\begin{large}
  {\bf Education}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Foreign Trade University, HCMC campus}\end{flushleft}
    \begin{flushright}Sep 2016 - Apr 2020\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}{Bachelor of Accounting \& Auditing}\end{flushleft}
    \begin{flushright}HCMC, SR Vietnam\end{flushright}
  \end{multicols}
\end{large}
```
\vspace{0.05cm}

<!-- Skills -->

```{=tex}
\begin{large}{\bf Skills}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
```
**Languages and Tools** - *proficient:* Python, R, Bash *intermediate:* Spark, SQL, Tensorflow/Keras, Git, Docker\
**Selected Coursework** - Deep Learning, Bayesian Machine Learning, Big Data Systems with Spark, Linear Models for Data Science, Statistical Learning, Data Engineering, Linear Algebra, Econometrics I & II, Data Visualization, Programming in Python

<!-- EXPERIENCE : 1ST BULLET-->

```{=tex}
\begin{large}{\bf Experience}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.vietcredit.com.vn/}{VietCredit Finance Company}}\end{flushleft}
    \begin{flushright}Feb 2022-Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Analyst, Risk management}\end{flushleft}
    \begin{flushright}HCMC, SR Vietnam\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
```
-   Conducted portfolio quality analysis, product risk management report, and other ad-hoc reports to support the manager in carrying out actionable recommendations regarding product policy, risk control, campaign efficiency, and account management;
-   Handed in data curation, wrangling, and reporting to maintain daily/monthly deliverables (PQA, early warning, KRIs report);
-   Participated in company’s digital transformations projects, monitored UAT for new
applications, assisted others dept. on daily operations.

\vspace{7pt}


